name: Android Build

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game (used for module description)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew assembleRelease --stacktrace
        
    - name: Verify APK exists
      run: |
        if [ -f app/build/outputs/apk/release/app-release.apk ]; then
          echo "APK file exists"
        else
          echo "APK file not found"
          exit 1
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ModMenu-${{ github.event.inputs.package_name }}
        path: app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
        retention-days: 90