name: Android Build

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game (used for module description)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew assembleRelease --stacktrace
        
    - name: Find APK
      run: |
        echo "Searching for APK files..."
        find app/build -name "*.apk" -type f
        
    - name: List build outputs
      run: |
        echo "Contents of app/build/outputs:"
        ls -R app/build/outputs/
        
    - name: Upload whatever is in outputs
      uses: actions/upload-artifact@v4
      with:
        name: ModMenu-${{ github.event.inputs.package_name }}
        path: app/build/outputs/
        if-no-files-found: warn