name: Android Library Build

on:
  workflow_dispatch:
    inputs:
      target_name:
        description: "Target name (for library description)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
        
    - name: Build native libraries
      run: |
        ./gradlew :app:externalNativeBuildRelease
        
    - name: Collect and package libraries
      run: |
        mkdir -p libs/armeabi-v7a
        mkdir -p libs/arm64-v8a
        cp -r app/build/intermediates/cmake/release/obj/armeabi-v7a/*.so libs/armeabi-v7a/
        cp -r app/build/intermediates/cmake/release/obj/arm64-v8a/*.so libs/arm64-v8a/
        cd libs
        zip -r ../libraries.zip *
        
    - name: Upload libraries
      uses: actions/upload-artifact@v4
      with:
        name: mod-libs-${{ github.event.inputs.target_name }}
        path: libraries.zip

    - name: Generate build info
      run: |
        echo "Build completed at $(date)" > build_info.txt
        echo "Target name: ${{ github.event.inputs.target_name }}" >> build_info.txt
        echo "Includes: ARMv7-a and ARM64-v8a libraries" >> build_info.txt